version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: gradle
    directory: /app
    schedule:
      interval: daily
  - package-ecosystem: gradle
    directory: /detection
    schedule:
      interval: daily
  - package-ecosystem: gradle
    directory: /wear
    schedule:
      interval: daily