default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play"
  lane :android do
    gradle(task: ":app:clean :app:bundle", build_type: "release")
    upload_to_play_store(track: "android-app")
  end
end

platform :android do
  desc "Deploy a new version to the Google Play"
  lane :wear do
    gradle(task: ":wear:clean :wear:bundle", build_type: "release")
    upload_to_play_store(track: "wear", aab: "./wear/build/outputs/bundle/release/wear-release.aab")
  end
end
